Repository WasiqB/coteafs-selenium, pull requests merged in 2019-05, with the labels that each got.

#31 Changes made for issue #28.
  src/main/java/com/github/wasiqb/coteafs/selenium/core/BrowserTest.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/ElementAction.java
Labels: bug

#34 Resolved Issue#30
  src/main/java/com/github/wasiqb/coteafs/selenium/config/AvailableBrowser.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/Browser.java
  src/main/resources/drivers/win/IEDriverServer.exe
Labels: enhancement

#36 Added Code of Conduct for contributors.
  CODE_OF_CONDUCT.md
Labels: community docs

#39 #14 | Wasiq Bhamla | Added contributing file.
  .github/CONTRIBUTING.md
Labels: community docs

#40 #35 | Wasiq Bhamla | Corrected sonarcloud issues.
  src/main/java/com/github/wasiqb/coteafs/selenium/config/ConfigUtil.java
  src/main/java/com/github/wasiqb/coteafs/selenium/constants/OS.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/Browser.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/BrowserActions.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/BrowserTest.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/ElementAction.java
  src/main/java/com/github/wasiqb/coteafs/selenium/listeners/DriverListner.java
Labels: bug

#44 Issue 43
  .circleci/config.yml
  src/main/java/com/github/wasiqb/coteafs/selenium/config/AvailableBrowser.java
Labels: bug

#47 Updated sonar command to run analysis on PR.
  .circleci/config.yml
Labels: enhancement

#49 Updated for tests on different browsers.
  src/main/java/com/github/wasiqb/coteafs/selenium/constants/ConfigKeys.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/Browser.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/BrowserTest.java
  testng-all-browsers.xml
Labels: test

#50 Develop
  .circleci/config.yml
  src/main/java/com/github/wasiqb/coteafs/selenium/constants/ConfigKeys.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/Browser.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/BrowserTest.java
  testng-all-browsers.xml
Labels: beta
