Repository WasiqB/coteafs-selenium, pull requests merged in 2019-07, with the labels that each got.

#64 Added support for Selenium WebDriver 4.0-alpha 2
  pom.xml
  src/main/java/com/github/wasiqb/coteafs/selenium/core/Browser.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/BrowserActions.java
Labels: enhancement

#65 Issue 37
  README.md
  assets/coteafs-selenium-logo.png
  assets/semver.png
  src/main/java/com/github/wasiqb/coteafs/selenium/core/BrowserActions.java
  src/test/java/com/github/wasiqb/coteafs/selenium/pages/action/LoginPageAction.java
Labels: community docs

#69 Sonar analysis on each branch
  .circleci/config.yml
Labels: sonar issues

#78 Fixed #77
  src/main/java/com/github/wasiqb/coteafs/selenium/core/BrowserPage.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/ElementAction.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/element/ISelectboxActions.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/enums/WaitStrategy.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/page/IPage.java
  src/test/java/com/github/wasiqb/coteafs/selenium/pages/action/NewAccountPageAction.java
Labels: bug, feature

#79 Added Safari browser support.
  src/main/java/com/github/wasiqb/coteafs/selenium/core/Browser.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/enums/AvailableBrowser.java
Labels: enhancement

#81 Release for v-2.1.0-Beta
  README.md
  src/main/java/com/github/wasiqb/coteafs/selenium/core/Browser.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/BrowserPage.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/ElementAction.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/element/ISelectboxActions.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/enums/AvailableBrowser.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/enums/WaitStrategy.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/page/IPage.java
  src/test/java/com/github/wasiqb/coteafs/selenium/pages/action/NewAccountPageAction.java
Labels: beta

#82 Release v-2.1.0
  README.md
  pom.xml
  src/main/java/com/github/wasiqb/coteafs/selenium/core/Browser.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/BrowserPage.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/ElementAction.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/element/ISelectboxActions.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/enums/AvailableBrowser.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/enums/WaitStrategy.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/page/IPage.java
  src/test/java/com/github/wasiqb/coteafs/selenium/pages/action/NewAccountPageAction.java
Labels: release

#90 Fixed #87, added isRunning method to IServiceAction interface.
  src/main/java/com/github/wasiqb/coteafs/selenium/core/Browser.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/BrowserActions.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/BrowserTest.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/driver/IDriver.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/driver/IDriverActions.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/driver/IServiceAction.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/element/IElementActions.java
Labels: feature

#91 Fixed #86, added new methods for saveScreenshots.
  src/main/java/com/github/wasiqb/coteafs/selenium/core/BrowserActions.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/BrowserTest.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/driver/IScreenAction.java
Labels: feature

#92 Fixed #84 by adding new methods for finding on element with wait strategy.
  src/main/java/com/github/wasiqb/coteafs/selenium/core/ElementAction.java
  src/main/java/com/github/wasiqb/coteafs/selenium/core/element/IElementActions.java
Labels: feature

#94 Fixed #85, updated method find and finds.
  src/main/java/com/github/wasiqb/coteafs/selenium/core/ElementAction.java
  src/test/java/com/github/wasiqb/coteafs/selenium/pages/MainPage.java
  src/test/java/com/github/wasiqb/coteafs/selenium/pages/SuccessPage.java
Labels: feature

#95 Update web driver version
  pom.xml
Labels: dependency upgrade
